export type LanguageOption = { code: string; label: string; native: string };

export const DEFAULT_LANGUAGE = "en";

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: "en", label: "English", native: "English" },
  { code: "af", label: "Afrikaans", native: "Afrikaans" },
  { code: "sq", label: "Albanian", native: "Shqip" },
  { code: "am", label: "Amharic", native: "አማርኛ" },
  { code: "ar", label: "Arabic", native: "العربية" },
  { code: "hy", label: "Armenian", native: "Հայերեն" },
  { code: "az", label: "Azerbaijani", native: "Azərbaycanca" },
  { code: "eu", label: "Basque", native: "Euskara" },
  { code: "be", label: "Belarusian", native: "Беларуская" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
  { code: "bs", label: "Bosnian", native: "Bosanski" },
  { code: "bg", label: "Bulgarian", native: "Български" },
  { code: "ca", label: "Catalan", native: "Català" },
  { code: "ceb", label: "Cebuano", native: "Cebuano" },
  { code: "zh-CN", label: "Chinese (Simplified)", native: "简体中文" },
  { code: "zh-TW", label: "Chinese (Traditional)", native: "繁體中文" },
  { code: "co", label: "Corsican", native: "Corsu" },
  { code: "hr", label: "Croatian", native: "Hrvatski" },
  { code: "cs", label: "Czech", native: "Čeština" },
  { code: "da", label: "Danish", native: "Dansk" },
  { code: "nl", label: "Dutch", native: "Nederlands" },
  { code: "eo", label: "Esperanto", native: "Esperanto" },
  { code: "et", label: "Estonian", native: "Eesti" },
  { code: "fi", label: "Finnish", native: "Suomi" },
  { code: "fr", label: "French", native: "Français" },
  { code: "fy", label: "Frisian", native: "Frysk" },
  { code: "gl", label: "Galician", native: "Galego" },
  { code: "ka", label: "Georgian", native: "ქართული" },
  { code: "de", label: "German", native: "Deutsch" },
  { code: "el", label: "Greek", native: "Ελληνικά" },
  { code: "gu", label: "Gujarati", native: "ગુજરાતી" },
  { code: "ht", label: "Haitian Creole", native: "Kreyòl Ayisyen" },
  { code: "ha", label: "Hausa", native: "Hausa" },
  { code: "haw", label: "Hawaiian", native: "ʻŌlelo Hawaiʻi" },
  { code: "he", label: "Hebrew", native: "עברית" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "hmn", label: "Hmong", native: "Hmong" },
  { code: "hu", label: "Hungarian", native: "Magyar" },
  { code: "is", label: "Icelandic", native: "Íslenska" },
  { code: "ig", label: "Igbo", native: "Igbo" },
  { code: "id", label: "Indonesian", native: "Bahasa Indonesia" },
  { code: "ga", label: "Irish", native: "Gaeilge" },
  { code: "it", label: "Italian", native: "Italiano" },
  { code: "ja", label: "Japanese", native: "日本語" },
  { code: "jw", label: "Javanese", native: "Basa Jawa" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ" },
  { code: "kk", label: "Kazakh", native: "Қазақша" },
  { code: "km", label: "Khmer", native: "ភាសាខ្មែរ" },
  { code: "rw", label: "Kinyarwanda", native: "Kinyarwanda" },
  { code: "ko", label: "Korean", native: "한국어" },
  { code: "ku", label: "Kurdish", native: "Kurdî" },
  { code: "ky", label: "Kyrgyz", native: "Кыргызча" },
  { code: "lo", label: "Lao", native: "ລາວ" },
  { code: "la", label: "Latin", native: "Latina" },
  { code: "lv", label: "Latvian", native: "Latviešu" },
  { code: "lt", label: "Lithuanian", native: "Lietuvių" },
  { code: "lb", label: "Luxembourgish", native: "Lëtzebuergesch" },
  { code: "mk", label: "Macedonian", native: "Македонски" },
  { code: "mg", label: "Malagasy", native: "Malagasy" },
  { code: "ms", label: "Malay", native: "Bahasa Melayu" },
  { code: "ml", label: "Malayalam", native: "മലയാളം" },
  { code: "mt", label: "Maltese", native: "Malti" },
  { code: "mi", label: "Maori", native: "Māori" },
  { code: "mr", label: "Marathi", native: "मराठी" },
  { code: "mn", label: "Mongolian", native: "Монгол" },
  { code: "my", label: "Myanmar", native: "မြန်မာ" },
  { code: "ne", label: "Nepali", native: "नेपाली" },
  { code: "no", label: "Norwegian", native: "Norsk" },
  { code: "ny", label: "Nyanja", native: "Chichewa" },
  { code: "or", label: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "ps", label: "Pashto", native: "پښتو" },
  { code: "fa", label: "Persian", native: "فارسی" },
  { code: "pl", label: "Polish", native: "Polski" },
  { code: "pt", label: "Portuguese", native: "Português" },
  { code: "pa", label: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "ro", label: "Romanian", native: "Română" },
  { code: "ru", label: "Russian", native: "Русский" },
  { code: "sm", label: "Samoan", native: "Gagana Samoa" },
  { code: "gd", label: "Scots Gaelic", native: "Gàidhlig" },
  { code: "sr", label: "Serbian", native: "Српски" },
  { code: "st", label: "Sesotho", native: "Sesotho" },
  { code: "sn", label: "Shona", native: "Shona" },
  { code: "sd", label: "Sindhi", native: "سنڌي" },
  { code: "si", label: "Sinhala", native: "සිංහල" },
  { code: "sk", label: "Slovak", native: "Slovenčina" },
  { code: "sl", label: "Slovenian", native: "Slovenščina" },
  { code: "so", label: "Somali", native: "Soomaali" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "su", label: "Sundanese", native: "Basa Sunda" },
  { code: "sw", label: "Swahili", native: "Kiswahili" },
  { code: "sv", label: "Swedish", native: "Svenska" },
  { code: "tl", label: "Tagalog", native: "Tagalog" },
  { code: "tg", label: "Tajik", native: "Тоҷикӣ" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "tt", label: "Tatar", native: "Татарча" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
  { code: "th", label: "Thai", native: "ไทย" },
  { code: "tr", label: "Turkish", native: "Türkçe" },
  { code: "tk", label: "Turkmen", native: "Türkmen" },
  { code: "uk", label: "Ukrainian", native: "Українська" },
  { code: "ur", label: "Urdu", native: "اردو" },
  { code: "ug", label: "Uyghur", native: "ئۇيغۇرچە" },
  { code: "uz", label: "Uzbek", native: "Oʻzbekcha" },
  { code: "vi", label: "Vietnamese", native: "Tiếng Việt" },
  { code: "cy", label: "Welsh", native: "Cymraeg" },
  { code: "xh", label: "Xhosa", native: "IsiXhosa" },
  { code: "yi", label: "Yiddish", native: "יידיש" },
  { code: "yo", label: "Yoruba", native: "Yorùbá" },
  { code: "zu", label: "Zulu", native: "IsiZulu" },
];

export function getLanguageLabel(code: string) {
  return LANGUAGE_OPTIONS.find((language) => language.code === code)?.native ?? "English";
}
